name: Maven Build Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Set up Java Development Kit (JDK)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21z' # Use JDK 8 or adjust to your required version
        distribution: 'adopt'

    # Configure Maven settings for custom repositories
    - name: Set up Maven settings
      run: echo "<settings>
        <profiles>
          <profile>
            <id>custom-repo</id>
            <repositories>
              <repository>
                <id>clas12maven</id>
                <url>https://clasweb.jlab.org/clas12maven/j4np/maven</url>
              </repository>
            </repositories>
          </profile>
        </profiles>
      </settings>" > ~/.m2/settings.xml

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean install -U -X

