name: Maven Build Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/settings.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Set up Maven settings
      run: |
        echo "<settings>
        <profiles>
          <profile>
            <id>custom-repo</id>
            <repositories>
              <repository>
                <id>clas12maven</id>
                <url>https://clasweb.jlab.org/clas12maven/j4np/maven</url>
              </repository>
            </repositories>
          </profile>
        </profiles>
        <activeProfiles>
          <activeProfile>custom-repo</activeProfile>
        </activeProfiles>
        </settings>" > ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn clean install -U -DskipTests
